language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t bringup/docker-react -f Dockerfile.dev .
script:
  - docker run bringup/docker-react npm run test -- --coverage 